### ISSUE TITLE
使用air报错

### ISSUE THREAD

**Issue by Sunrisies** [air-verse/air#660]
__    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.61.0, built with Go go1.23.2

watching .
!exclude tmp
building...
failed to build, error: exec: "cmd": executable file not found in %PATH%
running...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x10bd128]

goroutine 12 [running]:
github.com/air-verse/air/runner.(*Engine).runBin.func2()
        C:/Users/Lenovo/go/pkg/mod/github.com/air-verse/air@v1.61.0/runner/engine.go:543 +0x228
created by github.com/air-verse/air/runner.(*Engine).runBin in goroutine 11
        C:/Users/Lenovo/go/pkg/mod/github.com/air-verse/air@v1.61.0/runner/engine.go:522 +0xc5
![image](https://github.com/user-attachments/assets/b269dacf-ef39-4c1b-9c35-ac7e845d227c)

**Comment by cosmtrek** [comment]
please paste the air config

**Comment by Sunrisies** [comment]
我在当前目录下面没有生成默认的.air.toml文件，直接运行的，但是不管有没有这个配置文件都是报这个错误

**Comment by zccccc01** [comment]
## I meet the same problems in v1.61.0 , but I don't meet in v1.60.0
![error1](https://github.com/user-attachments/assets/254f326d-598a-47a9-a631-80e9704e5427)

## .air.toml
root = ".."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true

**Comment by xingdongzhe** [comment]
> failed to build, error: exec: "cmd": executable file not found in %PATH%

你把`cmd.exe`添加到 环境变量里面后，再试试看
